 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/financial_objects/payment_methods", type: :request do
  
  # FinancialObjects::PaymentMethod. As you add validations to FinancialObjects::PaymentMethod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FinancialObjects::PaymentMethod.create! valid_attributes
      get financial_objects_payment_methods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
      get financial_objects_payment_method_url(financial_objects_payment_method)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_financial_objects_payment_method_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
      get edit_financial_objects_payment_method_url(financial_objects_payment_method)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FinancialObjects::PaymentMethod" do
        expect {
          post financial_objects_payment_methods_url, params: { financial_objects_payment_method: valid_attributes }
        }.to change(FinancialObjects::PaymentMethod, :count).by(1)
      end

      it "redirects to the created financial_objects_payment_method" do
        post financial_objects_payment_methods_url, params: { financial_objects_payment_method: valid_attributes }
        expect(response).to redirect_to(financial_objects_payment_method_url(@financial_objects_payment_method))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FinancialObjects::PaymentMethod" do
        expect {
          post financial_objects_payment_methods_url, params: { financial_objects_payment_method: invalid_attributes }
        }.to change(FinancialObjects::PaymentMethod, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post financial_objects_payment_methods_url, params: { financial_objects_payment_method: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested financial_objects_payment_method" do
        payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
        patch financial_objects_payment_method_url(financial_objects_payment_method), params: { financial_objects_payment_method: new_attributes }
        payment_method.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the financial_objects_payment_method" do
        payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
        patch financial_objects_payment_method_url(financial_objects_payment_method), params: { financial_objects_payment_method: new_attributes }
        payment_method.reload
        expect(response).to redirect_to(financial_objects_payment_method_url(payment_method))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
        patch financial_objects_payment_method_url(financial_objects_payment_method), params: { financial_objects_payment_method: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested financial_objects_payment_method" do
      payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
      expect {
        delete financial_objects_payment_method_url(financial_objects_payment_method)
      }.to change(FinancialObjects::PaymentMethod, :count).by(-1)
    end

    it "redirects to the financial_objects_payment_methods list" do
      payment_method = FinancialObjects::PaymentMethod.create! valid_attributes
      delete financial_objects_payment_method_url(financial_objects_payment_method)
      expect(response).to redirect_to(financial_objects_payment_methods_url)
    end
  end
end
