 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/categories/category_incomes", type: :request do
  
  # Categories::CategoryIncome. As you add validations to Categories::CategoryIncome, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Categories::CategoryIncome.create! valid_attributes
      get categories_category_incomes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      category_income = Categories::CategoryIncome.create! valid_attributes
      get categories_category_income_url(categories_category_income)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_categories_category_income_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      category_income = Categories::CategoryIncome.create! valid_attributes
      get edit_categories_category_income_url(categories_category_income)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Categories::CategoryIncome" do
        expect {
          post categories_category_incomes_url, params: { categories_category_income: valid_attributes }
        }.to change(Categories::CategoryIncome, :count).by(1)
      end

      it "redirects to the created categories_category_income" do
        post categories_category_incomes_url, params: { categories_category_income: valid_attributes }
        expect(response).to redirect_to(categories_category_income_url(@categories_category_income))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Categories::CategoryIncome" do
        expect {
          post categories_category_incomes_url, params: { categories_category_income: invalid_attributes }
        }.to change(Categories::CategoryIncome, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post categories_category_incomes_url, params: { categories_category_income: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested categories_category_income" do
        category_income = Categories::CategoryIncome.create! valid_attributes
        patch categories_category_income_url(categories_category_income), params: { categories_category_income: new_attributes }
        category_income.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the categories_category_income" do
        category_income = Categories::CategoryIncome.create! valid_attributes
        patch categories_category_income_url(categories_category_income), params: { categories_category_income: new_attributes }
        category_income.reload
        expect(response).to redirect_to(categories_category_income_url(category_income))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        category_income = Categories::CategoryIncome.create! valid_attributes
        patch categories_category_income_url(categories_category_income), params: { categories_category_income: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested categories_category_income" do
      category_income = Categories::CategoryIncome.create! valid_attributes
      expect {
        delete categories_category_income_url(categories_category_income)
      }.to change(Categories::CategoryIncome, :count).by(-1)
    end

    it "redirects to the categories_category_incomes list" do
      category_income = Categories::CategoryIncome.create! valid_attributes
      delete categories_category_income_url(categories_category_income)
      expect(response).to redirect_to(categories_category_incomes_url)
    end
  end
end
